name: CI Pipeline

on:
  push:
    branches:
      - main
      - add-ci-cd-workflow
  pull_request:
    branches:
      - main
      - add-ci-cd-workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Current Directory:"
        pwd  # Mostra o diretório atual
        echo "Listing Files:"
        ls -la
        pytest test_suite.py
