name: CI Pipeline

on:
  push:
    branches:
      - main
      - add-ci-cd-workflow
  pull_request:
    branches:
      - main
      - add-ci-cd-workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run tests in openSUSE container
      uses: addnab/docker-run-action@v3
      with:
        image: opensuse/leap:latest
        options: --entrypoint "/bin/bash"
        run: |
          zypper refresh
          zypper install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip install pytest
          ls -la /var/lib/docker
          ls -la /usr/bin/docker
          ls -la /dev
          ls -la /home
          ls -la /tmp
          ls -la /usr/
          ls -la /mnt
          ls -la /github/workspace
          ls -la
          cd /github/workspace
          pytest test_suite.py
