name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run tests in openSUSE container
      uses: addnab/docker-run-action@v3
      with:
        image: opensuse/leap:latest
        options: --entrypoint "/bin/bash"
        run: |
          zypper refresh
          zypper install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip install pytest
          find / -type d -name linux_patch_audit
          ls -la /home/runner/work/linux_patch_audit
          cd /home/runner/work/linux_patch_audit
          ls -la
          pytest test_suite.py
