name: CI Pipeline

on:
  push:
    branches:
      - main
      - add-ci-cd-workflow
  pull_request:
    branches:
      - main
      - add-ci-cd-workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run tests in openSUSE container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace \
          -w /workspace opensuse/leap:latest /bin/bash -c "
          zypper refresh && \
          zypper install -y python3 python3-pip && \
          python3 -m pip install --upgrade pip && \
          pip install pytest && \
          ls -la && \
          pytest tests/test_suite.py
          "
